import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import JobsList from "@/components/JobsList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Increment decrement app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JobsList />
    </>
  );
}
